### ISSUE TITLE
升级不成功，应用程序状态变为“未安装”

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#10]
升级不成功，/opt/app/db/下面的文件就被删除了
导致已安装的程序变成“未安装”

**Comment by jinguojie-loongson** [comment]
根源：


/opt/app/db/999999：没有区分是升级的，还是新安装的，在安装错误时，都执行了rm

解决方案：
扩充/opt/app/db/999999字段：最后加一个install_type :: = {new_install, update}

另外发现一个Bug，分隔符使用了：，而时间里面也是有：

**Comment by jinguojie-loongson** [comment]
不用文本：
* 数据库：sqlite
* JSON格式

**Comment by jinguojie-loongson** [comment]
再加一个目录：

install：里面的内容：还是应用id为名称，内容只有2种：{new_install, update}

研究一下：python中直接处理sqlite3  http://www.cnblogs.com/yuxc/archive/2011/08/18/2143606.html

尝试：直接使用JSON：    /opt/app/install/id.json  内容是JSON语法

还是文本：现在cmd只能使用Shell命令，而Shell命令处理JSON不方便，所以还是使用文本。

**Comment by jinguojie-loongson** [comment]
时间字段：先去掉。

**Comment by jiangxinshang-loongson** [comment]
对于$.ajax请求来说，如果层级比较多，程序看起来会比较乱，而为了解决这种问题，才有了$when...done...fail...then的封装，它将$.ajax这嵌套结构转成了顺序平行的结果
补充：可以解决多个AJAX对应单个回调的问题，不能解决多层嵌套问题

**Comment by jinguojie-loongson** [comment]
1. 无意义的代码修改：
  排版上的修改，即使有必要做，也是单独另外commit，log一般写明“排版改进”
2. app_clear_status($btn,id)：理论上没有必要再加$btn参数，
  不需要手工调用refresh_app_status($btn,id);

经过讨论：原理已经清楚，Jiang的修改方式是正确的，
但是原来的一句不需要了

```
   if (status.indexOf("error") != -1)
   {
     app_button_change_status($btn, id, "not-installed");     <--- 应该是不需要，再验证
     warning_message(app_get_name(id) + app_get_button_text(status));

     app_clear_status(id);
   }
```

3. 还是有不正确的空格

```
+    if (errno == 0){
+    install_type = install_type + "-" + data;
+    };
```

4. app_clear_status()：
  对于update：现在是rm + echo，实际上只需要echo就可以。
