### ISSUE TITLE
评论功能：Ajax的comment参数要做URL转义

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#25]
否则，输入单引号时内容不正常。

**Comment by huangxg-loongson** [comment]
完成

**Comment by jinguojie-loongson** [comment]
编程启示：

1. $longdesc = addslashes($longdesc);
  任何文本型字段，都有必要在拼接SQL语句时执行这样的转义。

2. 第2种方式：
  参考Meedo框架：

  每一个字段的value，都要是string类型，都要做quote()
  “PDO提供了一个方法叫做quote，这个方法可以把输入字符串中带有引号的地方进行特殊字符转义。
”
  参考：http://www.jb51.net/article/68963.htm

**Comment by jiangxinshang-loongson** [comment]
测试：一个单引号仍然错误

**Comment by jiangxinshang-loongson** [comment]
总结：

AJAX HTTP传参：使用JSON
手写SQL：addslashes  ； 或者使用Meedo等数据库框架
读取SQL：不需要
页面展示：  &lt;script&gt;alert(&quot;hehe&quot;)&lt;/script&gt;      // 多数前端框架都会做这个工作

**Comment by jiangxinshang-loongson** [comment]
commet：标题

使用的主要技术：JSON

做的测试：  ' " & # 都可以

**Comment by jiangxinshang-loongson** [comment]
comment:  解决问题：当Ajax参数传递特殊字符时，传递参数缺失

使用的技术：JSON

做的测试：‘，’‘，？，《》，～，，！，@，#，￥，%，……，&，×，（），—， —，+等特殊字符都可以无缺失传递

**Comment by jinguojie-loongson** [comment]
页面展示： 使用PHP内置的htmlentities()
