### ISSUE TITLE
Apache+PHP的漏洞自动化检测

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#41]

**Comment by jinguojie-loongson** [comment]
参考：《6 Free PHP Security & Auditing Tools》
http://www.hotscripts.com/blog/6-free-php-security-auditing-tools/

**Comment by jiangxinshang-loongson** [comment]
PHP 安全 漏洞

**Comment by jiangxinshang-loongson** [comment]
安全问题的几种类型：
* Apache、PHP服务器的漏洞：通过操作系统升级
* PHP的SQl注入攻击：
  一些自动化工具
   + 人工分析系统（输入数据的单引号、双引号，必须转义）
   +  使用Meedo等框架
* 输入数据的漏洞：GET、POST、文本框
   vendorWorkbench.php传入一个GET参数，能够显示任意开发者的应用
* 业务安全：短时间内模拟大量下载

**Comment by jinguojie-loongson** [comment]
调研，确定3个进行试验。

**Comment by jinguojie-loongson** [comment]
做完写一个文章《龙芯平台PHP安全漏洞扫描工具》，市场部投搞

**Comment by jinguojie-loongson** [comment]
RIPZ： 这个工具发现的“可疑点”，通过grep _GET _POST _FILE基本也能达到相同效果。
  到本周日结束。
