### ISSUE TITLE
应用审核：页面改进

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#46]
开发者：面板显示更多字段、审核历史。
管理员：面板显示更多字段、审核操作。

**Comment by renyafei-loongson** [comment]
《测试报告》

测试用例：

《项目，操作，预期结果，是否通过》

  细化到：点哪个按钮，文本框里面填写什么值。

**Comment by jinguojie-loongson** [comment]
“预期结果”不能写数据库的变化，而是写界面上的所有变化。

例如：“下架”的应用，在前台页面不再出现，也要写进去。
即使现在没有实现的功能，只要是最终产品需要的，都要写进去。

**Comment by renyafei-loongson** [comment]
代码初步完成，待完整测试。
