### ISSUE TITLE
评论：XSS

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#56]
在应用详情页面，添加评论，内容填写

<script>alert("hehe")</script>

提交之后，每次都会显示对话框。

**Comment by jinguojie-loongson** [comment]
所有用户输入数据、又原样在页面上显示的变量，如果没有管理员审核，又没有技术检查，都会存在这个问题。
例如：提交应用时的“详细信息”。

**Comment by jinguojie-loongson** [comment]
参考：ask.loongnix.org的解决方法，
显示变量时，都要进行HTML转义：


```
<div class="content markitup-box">
  &lt;script&gt;alert(&quot;hehe&quot;)&lt;/script&gt;
</div>

```

![1](https://user-images.githubusercontent.com/25771159/28608272-572d2696-71a5-11e7-9258-02d9eafd0266.png)


![2](https://user-images.githubusercontent.com/25771159/28608278-608d5832-71a5-11e7-8f5d-926dfa6c7731.png)

**Comment by jiangxinshang-loongson** [comment]
php自带了转义函数：
1.http://blog.csdn.net/happy_jijiawei/article/details/52191098
2.两种转义函数htmlentities和htmlspecialchars 的区别：http://www.jb51.net/article/15527.htm

**Comment by jiangxinshang-loongson** [comment]
使用HTML Purifier解决XSS问题：http://willko.iteye.com/blog/475493

**Comment by jinguojie-loongson** [comment]
解决XSS，现在有两种类型：
1. 会修改原始的HTML   <-- 删除一些HTML标签，不可取
2. 严格保持原始的HTML不变
     “用户输入的，和后来输出的，看上去完全相同”

**Comment by jinguojie-loongson** [comment]
最后确定的方法：

* htmlentities和htmlspecialchars ：使用htmlentities，更严格。

**Comment by jinguojie-loongson** [comment]
加的位置不对：

（1）  数据库查询   ->  PHP变量     ：不应该做HTML转换
（2） PHP变量 在页面上显示  ：只在此处做HTML转换
