### ISSUE TITLE
审核信息列表：is_admin改成直观的文本

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#58]
标题：操作者
内容：管理员 / 账号名称

**Comment by jinguojie-loongson** [comment]
变量命名：

isExistAudit：    不清楚含义，似乎是“operation_type”
isappOfftheshelf：改成from_vendor
versionreview：review不需要



$operator = get_current_vendor();  只有在form_vendor时才调用

+    if($row[3] == 1 ){
 +      $isadmin = "管理员";
 +    }else{
 +      $isadmin =  get_vendor_name($row[6]);     // operator_name 
 +    }

不应该在显示的时候做，而是应该在insert时候做

**Comment by jinguojie-loongson** [comment]
代码质量的几个层次：

1. 功能正确  -  机器帮你检查
2. 排版专业  -  人眼检查
3. 命名合适  -  人脑检查
4. 重用性     -   人脑更复杂检查

**Comment by jinguojie-loongson** [comment]
为什么经常会发现不良的命名：

英文能力问题：句式，词汇 

“评论”   comment    review

by

根据ID更新OS

/* 注释 */   都是能看懂，
函数名称() 看不懂

**Comment by renyafei-loongson** [comment]
from_vendor：都改成is_admin
operation_type：现在使用0，1，2，  改成字符串
