### ISSUE TITLE
管理员登录：改成单页应用

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#60]

**Comment by jinguojie-loongson** [comment]
体会：

- 单页应用，尽可能在Javascript中完成页面跳转，form的action尽可能为空。
- 如果一定要使用Form的submit（主要是为了在敲回车时自动submit），method一定使用“GET”
  否则会出现的问题是：

 开发者登录 -> workbench -> 提交新应用 -> 使用浏览器按钮返回，出现错误提示“表单有提交数据”

**Comment by renyafei-loongson** [comment]
![1111url](https://user-images.githubusercontent.com/29266658/29411361-1c21877e-8387-11e7-928e-c0f4fc6ce216.png)
Form的method一定使用“GET”出现的问题：浏览器中的url传入了密码

**Comment by jinguojie-loongson** [comment]
bootstrap validator 也有后退出现“提交表单数据”的提示。
  先不支持按钮的回车事件。

**Comment by jinguojie-loongson** [comment]
1. 后退：没有错误提示
2. 按钮：还是需要鼠标点击
