### ISSUE TITLE
data目录：移到Web目录外面

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#62]
涉及的工作：
1。现在PHP中有写死的目录，“../”（有Jin的，也有Huang的），都要写到_config里面去。
2。《服务器备份规范》、《升级规范》要修改

**Comment by huangxg-loongson** [comment]
安装文档：

加一节“配置业务文件目录”
1、在服务器上创建业务文件目录，推荐使用“/opt/data”

cp  -rf   /var/www/html/app/data /opt/data

2. 加上必要的权限设置

chmod 777 /opt/data  -R

3. 修改配置文件  [ /var/www/html/app/php/_config.inc] 将其中的……改为……

**Comment by jinguojie-loongson** [comment]
1. 仿照getAppIcon.php：

   http://app.loongnix.org/app/php/getAppIcon.php?id=1
  返回的是一个图片

  所有data目录下文件的访问，都要使用上面的一个PHP接口。

2. 原来直接访问图片的，都要改成接口

vendorWorkbench.php:		     <img src='../data/icon/<?= $value['icon_file'] ?>' class="imgsize" />

3. getAppIcon.php里面的路径：

$HOT_DIR：要转移到_config.inc中。

4. PHP接口：只包含业务信息，不暴露内部目录结构

**Comment by jinguojie-loongson** [comment]
1. 不做无效的代码修改
  （不做和本问题无关的代码修改）
  一个commit：只包含与本任务有关的最少代码
  “最小化”
  习惯：在commit、push之前，自己把diff文件整个看一遍

2. file：太大，内涵不鲜明
3. $icon_url：现在input中暴露了服务器上的路径，有两处
   理想的实现：可以去除目录，只剩下文件名本身
