### ISSUE TITLE
sql.txt：调整基础数据

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#75]
基础数据：
* OS：有loongnix、中标32位、中标64位
* sql.txt：“应用公社”要做为一个默认的应用（app_file表）

**Comment by jinguojie-loongson** [comment]
还需要加入一个：“Loongnix”。
应用公社、以及其它所有APP提交时（app_file）至少要有Loongnix。

**Comment by renyafei-loongson** [comment]
中标桌面32位、中标桌面64位：暂时不写，以后真正上线使用了再收进来。
