### ISSUE TITLE
测试：升级

### ISSUE THREAD

**Issue by jinguojie-loongson** [jinguojie-loongson/loongson-app#94]
测试内容：
指定操作系统、提交了新版本
审核
客户端：只对提交了新版本的应用有“升级”按钮，信息显示正确，升级过程正确。

测试前提：
两台机器，模拟出不同的操作系统
技巧：还是使用loongnix， 只需要在其中一台机器上人工创建一个“/new.txt”，OS探测脚本看到这个文件就识别为一个不同的操作系统。

**Comment by huangxg-loongson** [comment]
1、上传新应用，安装，检查安装后文件内容是否正确。
2、上传新版本，审核通过后，卡片上显示“升级”。
3、修改探测脚本，刷新页面，卡片上的“升级”消失。
4、点击升级，检查升级后文件内容是否正确。

测试结果：多操作系统改版后，安装、升级正常。
