### ISSUE TITLE
php版本是5.3：评论内容转义用的函数，转义错误

### ISSUE THREAD

**Issue by huangxg-loongson** [jinguojie-loongson/loongson-app#99]
问题描述：在PHP5.3.3版本下，使用转义函数htmlentities()转义后，内容乱码
`$comment = htmlentities(get_app_comment($id));`

**Comment by jiangxinshang-loongson** [comment]
处理方法：

- 使用htmlspecialchars()函数替换函数htmlentities()
`$comment = htmlspecialchars(get_app_comment($id));`

**Comment by jiangxinshang-loongson** [comment]
处理方法：

- 为转义函数增加参数，指定字符串编码格式为UTF-8

- htmlentities()语法为：

`htmlentities(string,flags,character-set,double_encode) `

- 修改后的代码：
`$comment = htmlentities(get_app_comment($id), ENT_QUOTES, "UTF-8");`
参考：http://www.w3school.com.cn/php/func_string_htmlentities.asp
